name: Deploy

on:
  push:
    branches:
      - my-branch

jobs:
  deploy_zip:
    name: Deploy to project
    runs-on: ubuntu-latest
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read # This is required for actions/checkout
    steps:
      - uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          aws-access-key-id: my-aws-access-key-id
          aws-secret-access-key: my-aws-secret-access-key
          aws-region: us-east-1
      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install AWS CDK
        run: npm install -g aws-cdk

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy CDK
        run: |
          cd infra_saas/
          npm install
          cdk synth  apiAssets
          cdk deploy  apiAssets --require-approval never
